export const OPEN_DIRECTORY = 'OPEN_DIRECTORY';
export const CLOSE_DIRECTORY = 'CLOSE_DIRECTORY';
export const SELECT_DIRECTORY = 'SELECT_DIRECTORY';

export const CREATE_DIRECTORY = 'CREATE_DIRECTORY';
export const REMOVE_DIRECTORY = 'REMOVE_DIRECTORY';
